######################################################################
# Automatically generated by qmake (3.1) Tue Sep 5 10:21:02 2017
######################################################################

TEMPLATE = app
TARGET = checkers
INCLUDEPATH += .

QT += core gui widgets network

# Input
SOURCES += main.cc
